# server
server:
  port: 8888

# liquibase
liquibase:
  enabled: true
  change-log: classpath:/liquibase/db-changelog-master.xml
  drop-first: false

# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pthtwat
    username: root
    password: admin123
  jpa:
    show-sql: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true # could not initialize proxy - no Session
  http:
    multipart:
      maxFileSize: 800Mb
      maxRequestSize: 800Mb
      enabled: true
      location: /tmp
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
# date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
  mail:
    host: smtp.gmail.com
    port: 587
    username: luongvy4898@gmail.com
    password: '@nhVj1998'
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

# thymeleaf
    thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      content-type: text/html
      enabled: true
      encoding: UTF-8
      # excluded-view-names:
      mode: HTML5
      prefix: /templates/
      suffix: .html
      # template-resolver-order:
      # view-names:

# disable security
security:
  basic:
    enabled: false

# version
version: 0.1.0

errorReportReceiver: luongvy4898@gmail.com
errorReportCustomerReceiver: luongvy4898@gmail.com
isOnsendMailError: true
